### PR TITLE
The Next web

### PR DESCRIPTION
**Pull request by MakZ**
TWN Project Clone - RWD Design

### CODE REVIEW

**Review by Srjnnnn — CHANGES_REQUESTED** [review]
## Status: Changes Required :recycle: 

Hello team! You have a nice-looking app :muscle: . I like your style but before moving forward there are things to be done. :100: 

- [x]  First of all, please improve the Readme with more information about the app. You can use this [link ](https://github.com/microverseinc/readme-template) as a template.
- [x]  You haven't used grid in your CSS. I am checking the TSE guideline and it says at least one of your sections must be styled with the grid.
- [x]  Your pull-requests confused me. I saw this submission as a re-review but I can't see any review in that specific PR. Please keep going on from the same PR, don't open a new one while you are working on the project.

I think all in all you've made a really good job. After making those changes please submit for a re-review.
If you have any questions about the review, feel free to reach me via Slack. :100: 
_Eyüp Sercan UYGUR_

**Comment by Srjnnnn** [comment]
One more thing, I've just realized! Why are you trying to merge to another branch instead of the master branch? It is wrong GitHub flow!

**Comment by MakZ** [comment]
> One more thing, I've just realized! Why are you trying to merge to another branch instead of the master branch? It is wrong GitHub flow!

**Comment by MakZ** [comment]
> > One more thing, I've just realized! Why are you trying to merge to another branch instead of the master branch? It is wrong GitHub flow!

**Comment by Srjnnnn** [comment]
> One more thing, I've just realized! Why are you trying to merge to another branch instead of the master branch? It is wrong GitHub flow!

I've checked and didn't see any master or main branch. You've named your default branch with some custom name. If you can also change this name to master or main, that would solve the issue about the branches I think. If I'm making a mistake in here, you can reach out to me via Slack. :100:

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__Thank you for implementing the required changes highlighted by the previous reviewer :handshake:__
- Your Readme looks better :+1: 
- Your repository looks more professional :+1: 

__However, some changes are yet required before this milestone can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [x] As mentioned in one of the comments of the last reviewer, you do not have to rename the master branch. Your master branch name should remain as either `master` or `main`. It is difficult to identify your master branch at the moment because of your naming convention. Kindly rename your master branch.
- [x] Please include the `Getting Started` section in your Readme. This section should highlight the step-by-step process of setting up and running your project. You can find the details in the Readme template shared by the last reviewer.
- [x] The `MIT license` link in the License section of your Readme is broken. Kindly fix it.
- [x] In this milestone, usage of CSS grid in at least one section is enforced. This is also mentioned in the project specification, as seen in the image below:
original
- Although your implementation works, however, you have to demonstrate your knowledge of the CSS grid in this project by using it for one of the sections.

**[ OPTIONAL CHANGES ]**
- [x] You should improve your PR title and summary. Titles like `NYT Milestone-2`, `Milestone-2: New York Times`, or similar is best suitable for this PR. 
- Also, you should try to make your summary more descriptive: you can highlight the sections you implemented in this milestone.



* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Comment by ghost** [comment]
> ## Status: Changes Required ⚠️ 🚦
> ### Hello team 👋
> **Thank you for implementing the required changes highlighted by the previous reviewer 🤝**
> 
> * Your Readme looks better 👍
> * Your repository looks more professional 👍
> 
> **However, some changes are yet required before this milestone can be approved. Please check my comments below and fix them as appropriate.**
> 
> **[ REQUIRED CHANGES ]**
> 
> * [x]  As mentioned in one of the comments of the last reviewer, you do not have to rename the master branch. Your master branch name should remain as either `master` or `main`. It is difficult to identify your master branch at the moment because of your naming convention. Kindly rename your master branch.
> * [x]  Please include the `Getting Started` section in your Readme. This section should highlight the step-by-step process of setting up and running your project. You can find the details in the Readme template shared by the last reviewer.
> * [x]  The `MIT license` link in the License section of your Readme is broken. Kindly fix it.
> * [x]  In this milestone, usage of CSS grid in at least one section is enforced. This is also mentioned in the project specification, as seen in the image below:
>   original
> * Although your implementation works, however, you have to demonstrate your knowledge of the CSS grid in this project by using it for one of the sections.
> 
> **[ OPTIONAL CHANGES ]**
> 
> * [x]  You should improve your PR title and summary. Titles like `NYT Milestone-2`, `Milestone-2: New York Times`, or similar is best suitable for this PR.
> * Also, you should try to make your summary more descriptive: you can highlight the sections you implemented in this milestone.
> 
> **Please make the required changes and submit another review request when you are done.**
> 
> **Taofeek Olalere [Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
> **Happy Coding 😃**


# Status: Changes Required 🛑

### Hello team 👋,

**Great job on your project.**

### Highlights

- **The webpage looks like the original design.**

### Mandatory Requirements.

1). **Please implement the requested changes above. Hint: you can read this [article](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout) on how to implement CSS grid layout in your project.**


### Happy coding 🥂.

**You can reach me on slack (Rose Wanjohi).**

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @MakZ  & @MakZ**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [x] You have to add the "getting started" section in your readme, in which you explain how to setup your project locally.


---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Maksymilian Zuzel & Deep Kumar** 
Good job with the improvements for this project :muscle:  :muscle:
Your page meets most of the requirements :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:

- [x] Your project must have a breakpoint on 1024 pixels.
- [x] In the latest news section, use a header tag (hx) for the title of the section, that is also a link (a tag)
- [x] The title of each category section should be wrapped in a header tag (hx) and a link (a tag)
- [x] In the Latest deals section, use a header tag (hx) and  a link (a tag)
- [x] In the Latest deals section, each article has a title wrapped in a header tag (hx)
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Comment by Deepakdanger** [comment]
I have changed the code as per code review:-
1)Added the 1024px breakpoint.
2)Added hx tag and link to each title.

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi **TEAM**, great job on this project :+1: The README file is great :fireworks: The web app looks awesome :slightly_smiling_face: However, there are a few comments we need to address before proceeding :+1: Most of them were outlined in the previous reviews. Kindly check the comments below:
- Kindly the PR. The PR should have a title and a short description of the project. For information on the PR, we can check out this project description [link](https://microverse.pathwright.com/library/new-technical-curriculum/177956/path/step/104327801/)
- We are supposed to improve the use of HTML semantics, where we use `<section>` for like the "Latest News" section and the other 2 sections. We can also use the `<article>` tag for each of the children of the parent element <section>. Let us kindly read through the descriptions again
- Also we have more than 2 media queries breakpoints. Since we are using the mobile-first approach, for tablets we use `min-width around 768px`, and for desktops, we use `min-width around 1024px`. Kindly take note of the ***`min-width`***
- Let us avoid code repetition, for example `display: flex` repeats 10+ and some of the other properties values. Let us kindly improve it

[Optional]
- Let us try to have more descriptive commits since. Our commit messages must reflect what specifically we did when coding so that we can go back to it when we are faced with bugs :bug: 


Once these are fixed, kindly submit another code review request :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Review by christianotieno — APPROVED** [review]
### Milestone Approved :champagne:
Hello @MakZ & @Deepakdanger 👋 
 ##
This milestone has met all the requirements needed for approval. 👏 
Congratulations on the hard work done on this milestone. Good job 👍 
I will go ahead and mark this as complete. Good luck with the next tasks 🥇 
##
### Happy coding 💻 
#### Christian Otieno (CR)

**Pull request merged**
